llm_provider:
  type: azure_openai
  openai:
    api_key: >-
      sk-GyKldT8q9_Yv38pKLtftB1FCIw5LpTTBqNiRL0J5WXT3BlbkFJAgTht_k3cJImBmXds9eL2iD0RT17ultRDzkC2G1KgA
    model: gpt-4o
    temperature: 0
    max_tokens: 2000
  azure_openai:
    api_key: c386dc2a06864446b30400b232648635
    endpoint: https://gbs-poc-openai-001.openai.azure.com/
    deployment_name: gpt-4o-mini
    api_version: 2024-02-15-preview
    temperature: 0
    max_tokens: 2000
paths:
  input_folder: input
  output_folder: output
  input_file: test_cases.xlsx
  output_file_format: LLM_Judge_ResponseQuality_Results_{timestamp}.xlsx
evaluation:
  metrics:
    accuracy: true
    coherence: true
    relevance: true
    faithfulness: true
    bias: false
    toxicity: false
  scoring:
    excellent:
      min: 90
      max: 100
      color: green
    good:
      min: 75
      max: 89
      color: light_green
    moderate:
      min: 50
      max: 74
      color: amber
    poor:
      min: 0
      max: 49
      color: red
logging:
  level: INFO
  file: logs/llm_judge.log
